# Generated by Django 6.0.2 on 2026-04-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FreezerSensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100)),
                ('chip_mac', models.CharField(max_length=32)),
                ('temperature', models.FloatField()),
                ('battery_percent', models.FloatField()),
                ('current', models.FloatField()),
                ('energy', models.FloatField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['device_id', '-created_at'], name='freezer_dat_device__ca768b_idx'), models.Index(fields=['chip_mac', '-created_at'], name='freezer_dat_chip_ma_cc7fb0_idx'), models.Index(fields=['-created_at'], name='freezer_dat_created_1a8dee_idx')],
            },
        ),
    ]
