# Generated by Django 6.0.2 on 2026-05-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freezer_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freezersensordata',
            old_name='current',
            new_name='current_generation',
        ),
        migrations.RenameField(
            model_name='freezersensordata',
            old_name='energy',
            new_name='energy_generation',
        ),
        migrations.AddField(
            model_name='freezersensordata',
            name='batch_code',
            field=models.CharField(default=2.0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='freezersensordata',
            name='current_consumption',
            field=models.FloatField(default=2.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='freezersensordata',
            name='energy_consumption',
            field=models.FloatField(default=2.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='freezersensordata',
            name='network_signal',
            field=models.FloatField(default=2.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='freezersensordata',
            name='serial_number',
            field=models.CharField(default='SE-001', max_length=100),
            preserve_default=False,
        ),
    ]
