# Generated by Django 6.0.2 on 2026-05-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freezer_data', '0002_rename_current_freezersensordata_current_generation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Freezer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100)),
                ('batch_code', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('chip_mac', models.CharField(max_length=32)),
                ('status', models.IntegerField(choices=[(0, 'Off'), (1, 'On')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['serial_number'],
                'indexes': [
                    models.Index(fields=['device_id'], name='freezer_dat_device__a1b2c3_idx'),
                    models.Index(fields=['status'], name='freezer_dat_status_d4e5f6_idx'),
                ],
            },
        ),
    ]
