# Generated by Django 6.0.2 on 2026-07-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freezer_data', '0003_freezer'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='freezer',
            new_name='freezer_dat_device__cb81cb_idx',
            old_name='freezer_dat_device__a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='freezer',
            new_name='freezer_dat_status_170acb_idx',
            old_name='freezer_dat_status_d4e5f6_idx',
        ),
        migrations.AlterField(
            model_name='freezer',
            name='status',
            field=models.IntegerField(choices=[(0, 'Off'), (1, 'On')], default=1),
        ),
    ]
