# Generated by Django 6.0.2 on 2026-10-03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('freezer_data', '0004_rename_freezer_dat_device__a1b2c3_idx_freezer_dat_device__cb81cb_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freezer',
            name='client',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='assigned_freezers',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name='freezer',
            index=models.Index(fields=['client'], name='freezer_dat_client__7a8b9c_idx'),
        ),
    ]
