# Generated by Django 6.0.2 on 2026-10-05 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freezer_data', '0005_freezer_client'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='freezer',
            new_name='freezer_dat_client__f120fd_idx',
            old_name='freezer_dat_client__7a8b9c_idx',
        ),
    ]
